version: '3'

services:
  democracy-pwa:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: smallminds/democracy-pwa
    container_name: democracy-pwa
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`democracy.ryanfleck.ca`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=80"
      - "traefik.http.routers.portainer.service=democracy-pwa"
      - "traefik.http.routers.portainer.tls.certresolver=lets-encrypt"
